// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcywmdgI-i2Y8OX7dq02WXK-6m5VwQPmk',
    appId: '1:505791872937:web:faab8d38465551cadd0eb8',
    messagingSenderId: '505791872937',
    projectId: 'blood-donation-60c4b',
    authDomain: 'blood-donation-60c4b.firebaseapp.com',
    storageBucket: 'blood-donation-60c4b.appspot.com',
    measurementId: 'G-JXTR5YC7Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LbdOjJdQ6FplUsM_ZG-7hZScCMpRgmA',
    appId: '1:505791872937:android:b1006c8b089b4423dd0eb8',
    messagingSenderId: '505791872937',
    projectId: 'blood-donation-60c4b',
    storageBucket: 'blood-donation-60c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB441XkmOM16DMoHoGx4BtA0gFVb7djPhE',
    appId: '1:505791872937:ios:0c6682b96fef0011dd0eb8',
    messagingSenderId: '505791872937',
    projectId: 'blood-donation-60c4b',
    storageBucket: 'blood-donation-60c4b.appspot.com',
    iosClientId: '505791872937-o9cbm9ff907vuhcacnkqljv9fp0cr9bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB441XkmOM16DMoHoGx4BtA0gFVb7djPhE',
    appId: '1:505791872937:ios:0c6682b96fef0011dd0eb8',
    messagingSenderId: '505791872937',
    projectId: 'blood-donation-60c4b',
    storageBucket: 'blood-donation-60c4b.appspot.com',
    iosClientId: '505791872937-o9cbm9ff907vuhcacnkqljv9fp0cr9bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonation',
  );
}
